apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-lb
  namespace: mariadb
  annotations:
    metallb.universe.tf/address-pool: mariadb-pool
spec:
  type: LoadBalancer
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb

