apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: mariadb
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      name: mariadb-port
  selector:
    app: mariadb
  clusterIP: None
