apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
  namespace: mariadb
  labels:
    type: local
spec:
  storageClassName:
  capacity:
    storage: 300M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/backup/mariadb"
